version: '3.8'

services:
  # MinIO S3-compatible storage
  minio:
    image: minio/minio:latest
    container_name: blog_minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # MinIO API
      - "9001:9001"   # MinIO Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
      - ./storage/minio:/export
    networks:
      - blog_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Create default bucket for blog uploads
  minio-init:
    image: minio/mc:latest
    container_name: blog_minio_init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin123) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/blog-uploads;
      /usr/bin/mc policy set public myminio/blog-uploads;
      exit 0;
      "
    networks:
      - blog_network

volumes:
  minio_data:
    driver: local

networks:
  blog_network:
    driver: bridge
