version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: blogcms_mysql_prod
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:3306:3306"  # Bind hanya ke localhost untuk keamanan
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d:ro
      - ../backend/database_schema.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - blogcms_network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Backend Golang API
  backend:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    container_name: blogcms_backend_prod
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"  # Bind hanya ke localhost, nginx akan proxy
    environment:
      - SERVER_PORT=8080
      - APP_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE_HOURS=24
      - STORAGE_DRIVER=${STORAGE_DRIVER:-local}
      - UPLOAD_DIR=/app/storage/uploads
      - BASE_URL=${BASE_URL:-https://api.yourdomain.com}
      - STORAGE_MAX_FILE_SIZE=${STORAGE_MAX_FILE_SIZE:-5242880}
      # S3 settings (if using S3)
      - S3_ENDPOINT=${S3_ENDPOINT}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BASE_URL=${S3_BASE_URL}
      - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE:-true}
    volumes:
      # Mount upload directory for local storage
      - uploads_data:/app/storage/uploads
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - blogcms_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M

  # Adminer untuk Database Management
  adminer:
    image: adminer:4.8.1
    container_name: blogcms_adminer_prod
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:8080"  # Bind hanya ke localhost
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: pepa-linha-dark
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - blogcms_network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:1.25-alpine
    container_name: blogcms_nginx_prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
      # Mount uploads for serving static files (local storage only)
      - uploads_data:/var/www/uploads:ro
    depends_on:
      - backend
    networks:
      - blogcms_network
    command: nginx -g 'daemon off;'

volumes:
  mysql_data:
    driver: local
  uploads_data:
    driver: local

networks:
  blogcms_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
